name: carp_mobile_sensing_app
description: The CARP Mobile Sensing App
version: 2.0.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/apps/carp_mobile_sensing_app
publish_to: 'none' 

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"
  
platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter

  # CARP libraries
  carp_serializable: ^2.0.0       # polymorphic json serialization
  # carp_core: ^2.0.0               # the core CARP domain model
  # carp_mobile_sensing: ^0.30.6  # the CARP mobile sensing framework

  # CARP sampling packages
  #carp_connectivity_package: ^0.30.0
  #carp_context_package: ^0.30.1
  #carp_audio_package: ^0.30.0
  #carp_communication_package: ^0.30.0
  #carp_apps_package: ^0.30.0
  #carp_backend: ^0.30.0
  #carp_webservices: ^0.30.0

  # carp_health_package: ^2.0.0
  # carp_esense_package: ^0.30.2
  # carp_movisens_package: ^0.32.0
  # carp_polar_package: ^0.30.0
  # carp_movesense_package: ^0.30.0

  research_package: ^2.0.0

  # Packages used by CAMS. For some reason, we need to explicitly depend on them here.
  # Otherwise, the app will not launch or throws MissingPlugin Exceptions, even though 
  # it does compile. See issue #530
  system_info2: ^4.0.0
  path_provider: ^2.0.0
  sqflite: ^2.2.8                         # For local storage in SQLite DB
  permission_handler: '>=11.0.0 <13.0.0'  # For requesting permissions on Android and iOS
  shared_preferences: ^2.2.0
  package_info_plus: ^9.0.0
  flutter_local_notifications: ^21.0.0    # For sending notification on AppTask
  timezone: '>=0.10.0 <0.12.0'            # For collecting time zone information
  flutter_timezone: ^5.0.0                # For getting local time zone for scheduling notifications
  flutter_background: ^1.3.0              # For running background services on Android

  # probe-dependent plugins
  device_info_plus: ^12.1.0
  sensors_plus: ^7.0.0
  battery_plus: ^7.0.0
  pedometer: ^4.0.0       # Step count from local OS
  light: ^5.0.0           # Light sensor
  screen_state: ^5.0.0    # Screen LOCK/ON/OFF

  # For Bluetooth Low Energy (BLE) scanning and connection
  flutter_reactive_ble: ^5.0.0

  # Context package plugins
  location: ^8.0.1
  flutter_activity_recognition: ^4.0.0

  # Communication package plugins
  device_calendar: ^4.3.1 # need to use a forked version of device_calendar - see dependency_overrides below
  another_telephony: ^0.4.0
  call_e_log: ^0.0.4

  # Connectivity package plugins
  connectivity_plus: ^7.0.0    # connectivity events
  network_info_plus: ^7.0.0    # wifi ssid name
  flutter_blue_plus: '>=1.29.0 <3.0.0'  # bluetooth scan
  dchs_flutter_beacon: ^0.6.4  # collecting nearby iBeacon devices

  # Apps package plugins
  app_usage: ^4.0.0
  installed_apps: ^2.0.0

  # Audio package plugins
  flutter_sound: ^9.17.0  # audio probe
  noise_meter: ^5.0.0     # measuring noise level

  # wearable device plugins
  mdsflutter: ^2.3.1
  health: ^13.2.0
  polar: ^7.0.0

  # app-specific plugins
  flutter_launcher_icons: ^0.14.0


# Overriding carp libraries to use the local copy
dependency_overrides:
  # carp_serializable:
  #   path: ../../carp_serializable/
  carp_core:
    path: ../../carp_core/
  carp_mobile_sensing:
    path: ../../carp_mobile_sensing/
  carp_context_package:
    path: ../../packages/carp_context_package/
  carp_connectivity_package:
    path: ../../packages/carp_connectivity_package/
  carp_communication_package:
    path: ../../packages/carp_communication_package/
  carp_audio_package:
    path: ../../packages/carp_audio_package/
  carp_apps_package:
    path: ../../packages/carp_apps_package/
  carp_esense_package:
    path: ../../packages/carp_esense_package/
  carp_polar_package:
    path: ../../packages/carp_polar_package/
  carp_movisens_package:
    path: ../../packages/carp_movisens_package/
  carp_health_package:
    path: ../../packages/carp_health_package/
  carp_backend:
    path: ../../backends/carp_backend/
  carp_webservices:
    path: ../../backends/carp_webservices/
  carp_movesense_package:
    path: ../../packages/carp_movesense_package/
  # carp_cortrium_package:
  #   path: ../../../carp_cortrium_package/

  # research_package:
  #   path: ../../../../research.package/

  # esense_flutter:
  #   path: ../../../../flutter-plugins/packages/esense_flutter/
  
  # location:
  #   git:
  #     url: https://github.com/fairuzmn/flutterlocation.git
  #     ref: location-v5.5.0.0-dev.9-fix
  #     path: packages/location
  
  # due to this issue https://github.com/builttoroam/device_calendar/issues/586 
  device_calendar:
    git: https://github.com/bardram/device_calendar

  # due to this issue https://github.com/petri-lipponen-movesense/mdsflutter/issues/36 
  # mdsflutter:
  #   git:
  #     url: https://github.com/Panosfunk/mdsflutter.git
  #     ref: master

  # polar: 7.7.1
  # load polar from https://github.com/iarata/polar due to device_info_plus conflict
  # polar:
  #   git:
  #     url: https://github.com/iarata/polar.git
  #     ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter  
  test: any 
  flutter_lints: any
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# Is used to change the default app launch icons on iOS and Android.
# To install:
#  1. import the 'flutter_launcher_icons' package above
#  2. add the 'flutter_icons:' section below
#  3. run 'flutter pub get'
#  3. run 'flutter pub pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: "assets/cachet_logo.png"


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/study.png
    - assets/cachet_logo.png
    - assets/logo.png

