name: example
description: A example of how to use the carp_core library
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"
  
dependencies:
  carp_core:
    path: ../

dev_dependencies:
