name: carp_webservices_example
description: An small example of how to usee the CARP web service package.
homepage: https://github.com/cph-cachet/carp.sensing-flutter
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  carp_core: ^2.0.0
  carp_mobile_sensing: ^2.0.0
  qr_code_scanner_plus: ^2.0.12
  oidc: ^0.12.0

  # carp_core:
  #   path: ../../../carp_core
  # carp_mobile_sensing:
  #   path: ../../../carp_mobile_sensing
  carp_webservices:
    path: ../

dev_dependencies:
  test: any
  flutter_lints: any

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
